# Default values for thousandeyes-ea-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: thousandeyes

replicaCount: 1

image:
  repository: thousandeyes/enterprise-agent
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 49153
  protocol: UDP

resources:
  requests:
    memory: 2G
  limits:
    memory: 2G

nodeSelector: {}

tolerations: []

affinity: {}

volumeClaimTemplates:
  - metadata:
      name: thousandeyes-agent
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 500Mi
      # storageClassName:
  - metadata:
      name: thousandeyes-browserbot
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 500Mi
      # storageClassName: 
  - metadata:
      name: thousandeyes-log
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 500Mi
      # storageClassName: 
