apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            capabilities:
              add: ["NET_ADMIN","SYS_ADMIN"]
            seccompProfile:
              type: Localhost
              localhostProfile: te-seccomp.json
            appArmorProfile:
              type: Localhost
              localhostProfile: docker_sandbox
          args:
            - /sbin/my_init
          env:
            - name: TEAGENT_ACCOUNT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: thousandeyes-credentials
                  key: TEAGENT_ACCOUNT_TOKEN
            - name: TEAGENT_INET
              value: "4"
          volumeMounts:
            - name: thousandeyes-agent
              mountPath: /var/lib/te-agent
            - name: thousandeyes-browserbot
              mountPath: /var/lib/te-browserbot
            - name: thousandeyes-log
              mountPath: /var/log/agent
            - name: thousandeyes-shm-volume
              mountPath: /dev/shm
          ports:
            - containerPort: {{ .Values.service.port }}
              protocol: {{ .Values.service.protocol }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: thousandeyes-shm-volume
          emptyDir:
            medium: Memory
            sizeLimit: 512M
  {{- with .Values.volumeClaimTemplates }}
  volumeClaimTemplates:
    {{- toYaml . | nindent 4 }}
  {{- end }}
